### ISSUE TITLE
NPR Morning Edition feed is down

### ISSUE THREAD

**Issue by snarffalita** [pyther/podfeed#10]
The pyther feed looks good, but it's not pulling over to the podcast feed.

**Comment by pyther** [comment]
Hi @snarffalita. Can you provide a little more context here? The feeds appear to be getting updated and they are reflected in my podcast app.

**Comment by snarffalita** [comment]
Apologies, I am new to github and wasn't sure what would be helpful. I'm
using Podcast Republic and it says Morning Edition has not been updated
since yesterday, but pyther is showing content today.

**Comment by pyther** [comment]
Thanks for the additional context. I've identified the issue. The parser (in the code) looks for the `data-play-all` attribute in the website html and generates the feed based on that. For morning edition, the a data-play-all attribute is not generated for the current day. Therefore the morning edition will always be a day behind.

Looking at the parser code and the current structure of the NPR web pages, the parser needs to be reworked. Unfortunately, I won't have any time to work on that any time soon. While I would like say I'll be able to work on this within the next few weeks, realistically I probably won't have a chance to work on this for many months. Hopefully, someone else might be able to take a stab at this.

**Comment by pyther** [comment]
In theory, this should be fixed in https://github.com/pyther/podfeed/commit/5f4c7487fd036ee40d50ccd81b045d108fe0cd99. I changed the code to parse the current stories from the program page and the full episodes from previous days.

**Comment by pyther** [comment]
The last two days have appeared after airing. This appears fixed. Thanks for reporting the issue and let me know if there are any other problems.
