### ISSUE TITLE
NPR Morning Edition not updating

### ISSUE THREAD

**Issue by jlissemore** [pyther/podfeed#11]
The Morning Edition podcast is not updating today on Podcast Republic app. I appreciate any helpmor advice!

**Comment by pyther** [comment]
This is almost certainly related to https://github.com/pyther/podfeed/issues/10. In short, due to a code change made by NPR, Morning Edition will be behind by a day until someone gets a chance to rewrite the code. Unfortunately, I don't think I'll have the opportunity for a few months.

**Comment by jlissemore** [comment]
OK, thank you!

**Comment by pyther** [comment]
In theory, this should be fixed in https://github.com/pyther/podfeed/commit/5f4c7487fd036ee40d50ccd81b045d108fe0cd99. I changed the code to parse the current stories from the program page and the full episodes from previous days.

**Comment by jlissemore** [comment]
Thank you!

Jim Lissemore
Professor of Biology
Co-coordinator, Program in Population and Public Health
Biology Department
Dolan W241
John Carroll University
1 John Carroll Blvd.
University Heights, OH 44118
***@***.***
PHONE:216-397-4196

**Comment by pyther** [comment]
@jlissemore You're welcome. I deleted your comment since it included personal information that spammer would likely abuse.

**Comment by pyther** [comment]
The last two days have appeared after airing. This appears fixed. Thanks for reporting the issue and let me know if there are any other problems.
