### ISSUE TITLE
Some episodes of NPR All Things Considered getting shortened, all caps titles since late May/early June 2024

### ISSUE THREAD

**Issue by timweston** [pyther/podfeed#13]
Since late May/early June 2024, some episodes of NPR All Things Considered getting shortened, all caps titles.

I use Overcast and if you tap the title in the show notes, it takes you to the entry on NPR’s web site and displays a much nicer title.

I’m guessing something changed on NPR’s side of things.

Including some screenshots to show the strange titles.

![IMG_5347](https://github.com/pyther/podfeed/assets/4657234/6a59601c-01d6-4459-8093-3e1d840b1f21)
![IMG_5348](https://github.com/pyther/podfeed/assets/4657234/88ad8988-d62c-44be-be3f-86c281b2cda1)
![IMG_5349](https://github.com/pyther/podfeed/assets/4657234/edfcfbd5-d6ca-4f9c-a1e4-5b2c6ada724e)

**Comment by pyther** [comment]
Thanks for reporting the issue, but unfortunately this issue can't be fixed. This is an issue with the metadata for the embedded player. In this screenshot, you can see the title differs, and is in all CAPS, in the embedded player.
<img width="1413" alt="Screenshot 2024-06-16 at 12 42 42 AM" src="https://github.com/pyther/podfeed/assets/88368/55f6cf21-ef3d-41ef-8cb1-3581027880fa">

**Comment by timweston** [comment]
Thanks for the reply @pyther ; I’ll close the issue.
