### ISSUE TITLE
Feeds only pulling fraction of available episodes

### ISSUE THREAD

**Issue by jstetten** [pyther/podfeed#5]
Hello.

I realize this is a free side project of yours, but I've appreciated it for a long time!

I wonder if you noticed that a few days ago, the feeds stopped pulling most of the available episodes?

For instance, today, the Sunday Edition feed is only providing 5 of the 17 available episodes to download from NPR's website.

I don't know if it's a coincidence, but I noticed this started happeneing shortly after the time of your last commit. Any ideas?

**Comment by pyther** [comment]
Hi, thanks for the report. Last week, I discovered that KUOW offered podcast feeds and setup redirects for a few hours before realizing that their feeds were incomplete. Unfortunately, these temporary changes have caused confusion to some podcast clients.

I would recommend re-adding the feeds using the urls on https://nrfeed.pyther.net. These are new urls (.xml extension added) and should resolve issues with bad/stale cache.

**Comment by jstetten** [comment]
Thanks for the reply, @pyther. Waiting for the next weekend but so far, so good!
