### ISSUE TITLE
All Things Considered RSS on Google Podcasts

### ISSUE THREAD

**Issue by useranon404** [pyther/podfeed#8]
Whenever I try adding the RSS feed for All Things Considered, Google Podcasts loads the page for Fresh Air instead.

**Comment by pyther** [comment]
Thanks for reporting the issue. Unfortunately, this sounds to be a Google Podcast issue. I'm unable to reproduce the issue. In the web interface for Google Podcast, I am able to add the feed (https://feed.pyther.net/podcast/all-things-considered.xml) successfully. Is this still an issue for you?

**Comment by useranon404** [comment]
Thanks for the reply. I tried to add the feed again and was able to
successfully access the correct page. I don't know why previous attempts
with that same URL only loaded the Fresh Air feed.

**Comment by useranon404** [comment]
I just checked again and Google Podcasts changed the subscription again
from All Things Considered to Fresh Air. I tried unsubscribing and
subscribing again to the feed  (
https://feed.pyther.net/podcast/all-things-considered.xml), but the issue
is still unresolved. This issue is not reproducible on other podcast
platforms like Overcast.
