### ISSUE TITLE
All podcasts stopped updating on Sep 26th 2023

### ISSUE THREAD

**Issue by mgn0000** [pyther/podfeed#9]
All the NPR podcast feeds stopped updating on Sep 26th, 2023.

**Comment by pyther** [comment]
Thanks for reporting this, it looks like the NPR web page has changed which is causing error in the generation. Unfortunately, I won't be able to look into this until late next week.

**Comment by mgn0000** [comment]
Thanks for taking a look. Seems that "All Things Considered" does work, though it appears rather late most days.

**Comment by timweston** [comment]
This morning, the Morning Edition feed pulled in 100 episodes dating back to September 29.

Weekend Edition Saturday and Sunday did not pull in any episodes. I’m not sure about the Fresh Air feed, as I don’t subscribe to that through this service.

**Comment by brumleygap** [comment]
I've refreshed a few times and don't see anything other than ATC yet (using
Podcasts), but looking forward to having it back up and running.

**Comment by brumleygap** [comment]
I'm getting this error message on RSS validators for the Morning Edition feed (https://pca.st/podcast/b1483460-5db0-0137-f266-1d245fc5f9cf)
![Screenshot_20231006-081739-127](https://github.com/pyther/podfeed/assets/1946856/f882b390-dc84-4d0e-8d73-8143160592a5)

**Comment by snarffalita** [comment]
Morning Edition is updating once more, but Weekend Edition Saturday and Weekend Edition Sunday feeds still appear to be broken. Fresh Air and All Things Considered are fine.

**Comment by timweston** [comment]
Just received episodes of Weekend Edition Saturday from September 30 and October 7 in my podcast app (Overcast for iOS).

Nothing (yet) for Weekend Edition Sunday.

**Comment by mgn0000** [comment]
Matthew, or whoever fixed the tool,

Thanks, the main feeds work for me now, the weekend edition feeds don't appear though.

Matt

**Comment by pyther** [comment]
Sorry for the delay, I was on travel and didn't have the cycles to dig into this. This should be fixed with https://github.com/pyther/podfeed/commit/a832a174ad943de1040c6e10a5bd24879c857e9a. Podfeed was failing to find the publication date from the `media_url`. The `media_url` was changed for some stories and the new url did not contain a publication date. The new code will now fallback to parsing the `story_url`.
